### ISSUE TITLE
exits with KeyError: 'cpuacct.stat'

### ISSUE THREAD

**Issue by pgleghorn** [yadutaf/ctop#23]
Hi, Thanks for creating this nice tool.
For me it runs ok, screen refreshing, but sometimes after a few seconds exits without intervention, with:

```console
$ python /opt/ctop
Traceback (most recent call last):
  File "/opt/ctop", line 1043, in <module>
    main()
  File "/opt/ctop", line 1017, in main
    collect(measures)
  File "/opt/ctop", line 405, in collect
    cur[cgroup.name]['cpuacct.stat.diff'][key] = value - prev[cgroup.name]['cpuacct.stat'][key]
KeyError: 'cpuacct.stat'
```

I'm using:
- Python 2.7.12
- Docker version 1.12.2, build bb80604
- Ubuntu 16.04.1 LTS \n \l
- Linux monolith 4.4.0-47-generic #68-Ubuntu SMP 

Thx
Phil

[edit - also happens with python 3.5.2 ]

**Comment by yadutaf** [comment]
Thanks for using ctop and taking the time to fill this issue ! I suspect there is a race condition. Some cgroup is setup so that ctop detects it and creates the context. _Then_ ``cpuacct`` cgroup is created, _after_ the first iteration, and it does not have the full context.

Anyway that's an interesting issue to solve. I just pushed a commit on a fix branch, can you see if it fixes this issue ?

**Comment by pgleghorn** [comment]
Many thanks for your quick response. I'm not currently able to reproduce the issue using original version but will try this fix and let let you know when I can. Thanks, Phil

**Comment by yadutaf** [comment]
Closing as not confirmed on master. Thanks for the test.
